hide: true
title: Page/Services
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
      -
        display: Content
        fields:
          -
            handle: hero
            field:
              type: section
              display: Hero
          -
            handle: hero_heading
            field:
              type: text
              display: Heading
          -
            handle: hero_subheading
            field:
              type: textarea
              display: Subheading
          -
            handle: services
            field:
              type: section
              display: Services
          -
            handle: services_entries
            field:
              create: false
              collections:
                - pages
              type: entries
              display: Services
          -
            handle: cta
            field:
              type: section
              display: CTA
          -
            import: sections.cta
            prefix: cta_
  meta:
    display: Meta
    sections:
      -
        fields:
          -
            import: utilities.meta
      -
        display: 'Open Graph'
        fields:
          -
            import: utilities.open_graph
      -
        display: Sitemap
        fields:
          -
            import: utilities.sitemap
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - pages
              max_items: 1
              listable: false
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
              blueprint: true
              folder: templates/pages
